appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: iKbqC2GUoa3NSs653p78V27icQPX6d4Y6P6+jjOULNbu8lp5lfzgbgxDU/Mhl3uak2RAD33itYx7tMCJquAv9szXwqNxU3Tt29vmuyQro0Fi42JTW2m1Ti8pE4gQ5YyBuj48teG0+f1BGGMOuhd01zOjCFq0CrYIdSZet5GNVVfEJMuBph0Yrojie9+hDHPeMYGKP4FWxCLmgsm9hSeJ9yylvqEdSfwFH4LKeRWPAYlVbgd4ghSQcAiWO3QtJi4CTBf2VWwfiaDVoQ/+BZ7QR2Y4GEd8wi/fl1ageEQDkwcNglcBPL+TPjGI0OEXI/c0IIGTtqJULTH3e6zWkOiPY6Qgm3nkrhlDKnVvgFzkl/9CNYOEJYzxNYtxZKxfzNebDOnDghTJ00HrPVl+eNG6TD//311HFwHHOZBv1UU5SjnJYDCtuLsLEa7kjQ2W0iRGhhAH9N3frVcKPmruc5DgIt4SBO0KcQHM39B/bmXGIHBMsqIwc4+ROu+DqEUMKZ22qMX/jlgaFVa1LkM2Y994XO3vhHp9PLYbVT0UETTeRmPLiydIUhpuYXvzT3/2pphIRgwsHkM9F52XAuqOgRaGkRPoKp8ORvSgPBoX4t/R+dJIEOJNBFg2dBi+LPpcdnAdl/MxjEuW9l+51+eNfnYrCcYNNIePmTf/NHCmOPyMOL4=}
conda_forge_output_validation: true
