travis:
  secure:
    BINSTAR_TOKEN: LBC4WXujwHjP4YDrDlZyDMx/oKXhN19n3ZBf1g9I/JY3RiYlH5m74LNcIKj8UdnIXf8KLMwKwTw9IFlD2ybwfTCNfjSNrA9TK6HA0d0Ph+fAyOxzupno7+Ch9WUYJdxJo5CXrkVzbfe+UpKrEs0yB4Z0DN9FRm5nnrLQqHkL0lNTTZTwTVYM0PI3YAmp2E23TRwjepxHd/PSvK0FlyQ0eUeTS4fhSo6NpkIR4+eXs6M4++gKv+/ck6j76J05WuO4EqiCh/QzU1T8OBCfGzddrpQOYC5P344x0SCikb1djN8DBjpW5tSnB2RY4HY6SKgg6OmmJka3MDLwDGTM6k7JLulwXgD9kBhEMMHfZ1zUDP1qO3F/peF4/QTOIC5vSLiZZMeWRAW1SGWI5vgrLV55us71SDgvCt/56sXYnTwgZmoF4gA2bz9aPDl09ID0g4DvH417Mh87qglfYSCjqqzuYYOMU5yIA61U9oMHdNmrsiei5WpH0Gb3+JTZQmlxQ9Tk/e6qz0m+V4Au/n7KTQxNpQU8zusqqEatUFUslDEwBIZc+b+HkeU2gfsa06TPe4hNepQKne/SettycM3ue8eqw3113noJcpfI3cvlD/xxIa+oEdZr1nTNVgpXjFIkjkC6YshQdo8b4KEQ6q7mbdTyXbCCGaNF3q7irAJnaORlH5M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
